# Generated by Django 5.1.7 on 2025-03-29 01:59

import django.contrib.postgres.fields
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        # add this to create the extension in our DB
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector;', reverse_sql='DROP EXTENSION IF EXISTS vector;'),

        migrations.CreateModel(
            name='Documents',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.IntegerField()),
                ('chunk_id', models.IntegerField()),
                ('clean_text', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='Vector embeddings generated using MiniLM-L6-v2')),
            ],
        ),
    ]
